// FILE: com/winlator/cmod/core/DownloadProgressDialog.java
// This is the reconstructed Java source equivalent of the patched smali.
// For APK integration: the smali files in patches/smali_classes10/ are the
// production-ready form. This Java source is for reference only.

package com.winlator.star.core;

import android.app.Activity;
import android.app.Dialog;
import android.graphics.drawable.ColorDrawable;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.ProgressBar;
import android.widget.TextView;

import com.winlator.star.MainActivity;
import com.winlator.star.R;
import com.winlator.star.math.Mathf;

public class DownloadProgressDialog {
    private final Activity activity;
    private Dialog dialog;

    public DownloadProgressDialog(Activity activity) {
        this.activity = activity;
    }

    private void create() {
        if (dialog != null) return;

        dialog = new Dialog(activity, 0x1030011); // Theme_Dialog
        dialog.requestWindowFeature(Window.FEATURE_NO_TITLE); // 1
        dialog.setCancelable(false);
        dialog.setCanceledOnTouchOutside(false);
        dialog.setContentView(R.layout.download_progress_dialog);

        Window window = dialog.getWindow();
        if (window != null) {
            // Remove title bar and status bar flags
            window.clearFlags(0x10); // FLAG_DIM_BEHIND
            window.clearFlags(0x8);  // FLAG_BLUR_BEHIND

            // Full-screen: MATCH_PARENT x MATCH_PARENT
            window.setLayout(-1, -1);

            // Transparent background (removes dialog chrome/rounded card)
            window.setBackgroundDrawable(new ColorDrawable(0));

            // Allow auto-rotation (sensor-based) — ActivityInfo.SCREEN_ORIENTATION_SENSOR = 4
            WindowManager.LayoutParams params = window.getAttributes();
            params.screenOrientation = 4;
            window.setAttributes(params);
        }
    }

    public void show() {
        show((Runnable) null);
    }

    public void show(int textResId) {
        show(textResId, null);
    }

    public void show(Runnable onCancelCallback) {
        show(0, onCancelCallback);
    }

    public void show(int textResId, Runnable onCancelCallback) {
        if (isShowing()) return;
        close();

        if (dialog == null) create();

        if (textResId > 0) {
            ((TextView) dialog.findViewById(R.id.TextView)).setText(textResId);
        }

        setProgress(0);

        if (onCancelCallback != null) {
            dialog.findViewById(R.id.BTCancel)
                  .setOnClickListener(v -> onCancelCallback.run());
            dialog.findViewById(R.id.LLBottomBar)
                  .setVisibility(View.GONE);
        }

        dialog.show();
    }

    public void setProgress(int progress) {
        if (dialog == null) return;
        progress = Mathf.clamp(progress, 0, 100);

        ((ProgressBar) dialog.findViewById(R.id.CircularProgressIndicator))
            .setProgress(progress);

        ((TextView) dialog.findViewById(R.id.TVProgress))
            .setText("正在安装... " + progress + "%");
    }

    public void close() {
        try {
            if (dialog != null) dialog.dismiss();
        } catch (Exception e) { /* ignored */ }
    }

    public void closeOnUiThread() {
        // Posts showPermissionsButton() on UI thread via Lambda0
        // (patched: was close(), now calls showPermissionsButton())
        activity.runOnUiThread(this::showPermissionsButton);
    }

    public boolean isShowing() {
        return dialog != null && dialog.isShowing();
    }

    /**
     * NEW METHOD (added in splash integration).
     *
     * Called when installation completes (via closeOnUiThread → Lambda0).
     * Makes the "All Files Access Required" button visible and wires it to
     * Lambda2 → close() + MainActivity.doPermissionsFlow().
     */
    public void showPermissionsButton() {
        if (dialog == null) return;

        // Show the bottom bar (LLBottomBar)
        View llBottomBar = dialog.findViewById(R.id.LLBottomBar);
        if (llBottomBar != null) llBottomBar.setVisibility(View.VISIBLE);

        // Wire the "All Files Access Required" button
        View btnCancel = dialog.findViewById(R.id.BTCancel);
        if (btnCancel == null) return;

        btnCancel.setOnClickListener(v -> {
            close();
            ((MainActivity) activity).doPermissionsFlow();
        });
    }

    // -------------------------------------------------------------------------
    // Synthetic lambdas (generated by D8 / R8 — do NOT write by hand)
    // -------------------------------------------------------------------------
    // Lambda0: Runnable — used by closeOnUiThread()
    //   run() → this.showPermissionsButton()     [PATCHED: was close()]
    //
    // Lambda1: View.OnClickListener — wraps a Runnable
    //   onClick(v) → runnable.run()
    //
    // Lambda2: Runnable — used by showPermissionsButton()
    //   run() → this.close(); ((MainActivity)activity).doPermissionsFlow()
}
